### ISSUE TITLE
Optifine not working

### ISSUE THREAD

**Issue by JEijiandrei** [GoodDay360/Tempest-Launcher#2]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.18 (C:\Users\administrator\AppData\Roaming\.minecraft\mods\OptiFabric.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\administrator\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.18, reason: to remove
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

this is the crash log

**Comment by GoodDay360** [comment]
Thank I will check it.
